# Generated by Django 5.0.14 on 2026-09-03 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_familymember'),
        ('appointments', '0003_appointment_serial_number'),
        ('doctors', '0005_chambersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('vitals', models.JSONField(blank=True, default=dict, help_text="e.g. {'bp': '120/80', 'pulse': '72', 'weight': '70', 'temp': '98.6', 'blood_sugar': '6.2'}")),
                ('diagnostic_tests', models.TextField(blank=True, default='', help_text='e.g. CBC, Lipid Profile, USG of Whole Abdomen')),
                ('advice', models.TextField(blank=True, default='', help_text='General lifestyle & dietary instructions')),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='accounts.familymember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('medication_name', models.CharField(help_text='e.g. Tab. Napa 500mg (Paracetamol)', max_length=200)),
                ('dosage', models.CharField(default='1 + 0 + 1', help_text='e.g. 1 + 0 + 1 or 1 + 1 + 1', max_length=50)),
                ('timing', models.CharField(default='After Meal', help_text='e.g. After Meal, Before Meal', max_length=50)),
                ('duration', models.CharField(default='7 Days', help_text='e.g. 7 Days, 1 Month, Continue', max_length=50)),
                ('instructions', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescribed Medication',
                'verbose_name_plural': 'Prescribed Medications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('brand_name', models.CharField(db_index=True, max_length=150)),
                ('generic_name', models.CharField(db_index=True, max_length=150)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROP', 'Eye/Ear Drop'), ('CREAM', 'Ointment/Cream'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('strength', models.CharField(blank=True, default='', max_length=50)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['brand_name'],
                'unique_together': {('brand_name', 'strength')},
            },
        ),
    ]
