# Generated by Django 5.0.14 on 2026-09-03 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_familymember'),
        ('appointments', '0003_appointment_serial_number'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(help_text='e.g. Complete Blood Count (CBC) with ESR', max_length=200)),
                ('report_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test (CBC, HbA1c, Lipid)'), ('IMAGING', 'Imaging (X-Ray, USG, MRI, CT)'), ('CARDIOLOGY', 'Cardiology (ECG, Echo, ETT)'), ('PATHOLOGY', 'Pathology & Biopsy'), ('PRESCRIPTION_SCAN', 'Previous Prescription Scan'), ('OTHER', 'Other Diagnostic Report')], db_index=True, default='BLOOD_TEST', max_length=30)),
                ('diagnostic_center', models.CharField(blank=True, default='', help_text='e.g. Popular Diagnostic, Ibn Sina, Labaid, Square', max_length=150)),
                ('test_date', models.DateField(db_index=True)),
                ('file_url', models.URLField(help_text='Document or Cloudinary scan URL', max_length=500)),
                ('summary_notes', models.TextField(blank=True, default='', help_text='Key values, e.g. HbA1c: 7.4%, Total Cholesterol: 220 mg/dL')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='accounts.familymember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
