# Generated by Django 5.0.14 on 2026-09-30 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('appointments', '0005_appointment_emergency_reason_and_more'),
        ('prescriptions', '0002_medicalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='Pulse Rate (bpm)', null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='mmol/L', max_digits=5, null=True)),
                ('glucose_type', models.CharField(choices=[('RBS', 'Random Blood Sugar'), ('FBS', 'Fasting Blood Sugar'), ('2HABF', '2 Hours After Breakfast')], default='RBS', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm)', max_digits=5, null=True)),
                ('temperature_f', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature (°F)', max_digits=5, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='Blood Oxygen SpO2 (%)', null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_logs', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_logs', to='accounts.familymember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_logs', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_logs', to='prescriptions.prescription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Vital Log',
                'verbose_name_plural': 'Patient Vital Logs',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
