# Generated by Django 5.0.14 on 2026-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_patientvitallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending Analysis'), ('PROCESSING', 'Analyzing via AI'), ('COMPLETED', 'Analysis Complete'), ('FAILED', 'Analysis Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_doctor_questions',
            field=models.JSONField(blank=True, default=list, help_text='Recommended questions for patient to discuss with their doctor'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_extracted_parameters',
            field=models.JSONField(blank=True, default=list, help_text='Structured array of extracted lab parameters with units, normal reference ranges, and flags'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_risk_level',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ATTENTION_NEEDED', 'Attention Needed'), ('HIGH_RISK', 'High Risk')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_summary_bn',
            field=models.TextField(blank=True, default='', help_text='সহজ বাংলায় রোগীর জন্য ফলাফল ব্যাখ্যা'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ai_summary_en',
            field=models.TextField(blank=True, default='', help_text='AI generated clinical summary in English'),
        ),
    ]
