# Generated by Django 5.0.14 on 2026-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_medicalreport_ai_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Recommended next consultation date', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_notes',
            field=models.CharField(blank=True, default='', help_text='e.g. Come with CBC report after 7 days', max_length=255),
        ),
    ]
