# Generated by Django 5.0.14 on 2026-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLINIC_ADMIN', 'ClinicAdmin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], db_index=True, default='PATIENT', max_length=20),
        ),
    ]
