# Generated by Django 5.0.14 on 2026-09-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
