# Generated by Django 5.0.14 on 2026-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='serial_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
