# Generated by Django 5.0.14 on 2026-09-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_arrived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
