# Generated by Django 5.0.14 on 2026-09-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_arrived_at_appointment_is_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='emergency_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
