# Generated by Django 5.0.14 on 2026-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_user_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of medical license/certificate', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='requested_by_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorclinic',
            name='status',
            field=models.CharField(choices=[('PENDING_DOCTOR_APPROVAL', 'Pending Doctor Approval'), ('PENDING_CLINIC_APPROVAL', 'Pending Clinic Approval'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='ACCEPTED', max_length=30),
        ),
    ]
