# Generated by Django 5.0.14 on 2026-09-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_certificate_url_doctor_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorclinic',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Clinic Mapping', 'verbose_name_plural': 'Doctor Clinic Mappings'},
        ),
    ]
