# Generated by Django 5.0.14 on 2026-09-03 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinicdepartment_options'),
        ('doctors', '0004_alter_doctorclinic_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('session_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_TRANSIT', 'In Transit'), ('IN_CHAMBER', 'In Chamber'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('current_serial', models.PositiveIntegerField(default=0)),
                ('estimated_mins_per_patient', models.PositiveIntegerField(default=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamber_sessions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamber_sessions', to='doctors.doctor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamber Session',
                'verbose_name_plural': 'Chamber Sessions',
                'ordering': ['-session_date'],
                'unique_together': {('doctor', 'clinic', 'session_date')},
            },
        ),
    ]
