# Generated by Django 5.0.14 on 2026-09-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinicdepartment_options'),
        ('doctors', '0005_chambersession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'clinic', 'day_of_week')},
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patients',
            field=models.PositiveIntegerField(default=20, help_text='Maximum patients per session'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Duration of each consultation slot in minutes'),
        ),
    ]
