# Generated by Django 5.0.14 on 2026-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambersession',
            name='announcement_note',
            field=models.CharField(blank=True, default='', help_text='e.g. Stuck in Mohakhali traffic, arriving at 6:30 PM', max_length=255),
        ),
        migrations.AddField(
            model_name='chambersession',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Broadcasted delay e.g. 20 mins due to traffic/OT'),
        ),
        migrations.AddField(
            model_name='chambersession',
            name='room_number',
            field=models.CharField(blank=True, default='', help_text='e.g. Room 304, 3rd Floor', max_length=50),
        ),
        migrations.AddField(
            model_name='chambersession',
            name='skipped_serials',
            field=models.JSONField(blank=True, default=list, help_text='List of skipped/held patient serial numbers'),
        ),
        migrations.AlterField(
            model_name='chambersession',
            name='estimated_mins_per_patient',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='chambersession',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_TRANSIT', 'In Transit'), ('IN_CHAMBER', 'In Chamber'), ('PRAYER_BREAK', 'Prayer / Namaz Break'), ('EMERGENCY', 'Emergency Round'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], db_index=True, default='NOT_STARTED', max_length=20),
        ),
    ]
