# Generated by Django 5.0.14 on 2026-09-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_emergency_reason_and_more'),
        ('doctors', '0007_chambersession_announcement_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambersession',
            name='active_emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_emergency_sessions', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='chambersession',
            name='held_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_patient_sessions', to='appointments.appointment'),
        ),
    ]
