import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Nav
    home: "Home",
    doctors: "Doctors",
    clinics: "Clinics",
    bookAppointment: "Book Appointment",
    dashboard: "Dashboard",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    notifications: "Notifications",
    noNotifications: "No new notifications",

    // Navigation & Workspace
    accountSettings: "Account Settings",
    clinicalWorkspace: "Clinical Workspace",
    clinical: "Clinical",
    clinicAffiliations: "Clinic Affiliations",
    affiliations: "Affiliations",
    chamberSchedule: "Chamber Schedule",
    schedule: "Schedule",
    doctorCredentials: "Credentials & License",
    credentials: "Credentials",
    erxAndVitals: "E-Rx & Vitals",
    medicalReports: "Reports",
    chamberQueue: "Queue",

    // Reception Desk
    receptionist_console: "Reception Desk Console",

    // Patient Dashboard
    patientDashboard: "Patient Dashboard",
    patientDashboardSubtitle: "Live serial tracker, appointments, & family care",
    myAppointments: "My Appointments",
    familyProfiles: "Family Profiles",
    addFamilyMember: "Add Family Member",
    noAppointments: "No Booked Appointments",
    noAppointmentsHint: "You haven't scheduled any doctor consultations yet.",
    bookNow: "Book an Appointment Now",

    // Serial Tracker
    liveSerialTracker: "LIVE SERIAL TRACKER",
    doctorStatus: "Doctor Status:",
    refreshesAuto: "Refreshes automatically ⏱️",
    currentlyCalled: "Currently Called",
    yourSerial: "Your Serial #",
    patientsAhead: "Patients Ahead",
    estWait: "Est. Wait",
    yourTurn: "Your Turn!",
    itsYourTurn: "🎉 IT'S YOUR TURN! Please proceed into",
    consultationRoom: "'s consultation room now.",
    getReady: "🔔 GET READY: You are only",
    patientsAway: "patient(s) away! Please report to clinic waiting lounge.",

    // Appointment card
    serialBadge: "Serial #",
    forPatient: "For:",
    pendingPayment: "Pending Payment",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    payAndConfirm: "Pay & Confirm",
    cancel: "Cancel",
    viewPrescription: "View E-Prescription",
    leaveReview: "Leave a Review",

    // Payment
    processPayment: "Process Payment",
    amountPayable: "Amount Payable",
    selectPaymentMethod: "Select Payment Method",
    enterTrxId: "Enter Transaction ID (TrxID) *",
    cashAtChamberNote: "Cash at Clinic Counter: Your appointment will remain payment-pending until the clinic reception confirms the cash payment.",
    confirmPayment: "Confirm Payment",
    confirming: "Confirming...",

    // Family
    parentCareTitle: "Parent Care & Family Profiles",
    parentCareSubtitle: "Add parents, spouse, or children to manage their appointments & health history.",
    addMember: "Add Member",
    noFamilyMembers: "No Family Members Added",
    noFamilyHint: "Add your parents or dependents to book appointments for them easily.",
    fullName: "Full Name",
    relationship: "Relationship",
    phone: "Phone Number (BD)",
    age: "Age",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    bloodGroup: "Blood Group",
    medicalNotes: "Medical Notes / History",
    saveMember: "Save Member",
    editMember: "Edit Family Member",
    updateMember: "Update Member",
    deleteMember: "Delete",
    confirmDeleteMember: "Are you sure you want to remove this family member?",
    saving: "Saving...",

    // Prescription
    officialPrescription: "Official Digital E-Prescription",
    printPdf: "Print / PDF",
    qrVerified: "QR VERIFIED",
    scanToVerify: "Scan to Verify",
    recommendedTests: "Recommended Lab Tests:",
    doctorAdvice: "Doctor Advice:",
    prescribedMedicines: "Rx (Prescribed Medicines)",
    rxVerificationTitle: "Official E-Prescription Verification",
    rxVerificationSubtitle: "Government & DGDA Compliant Digital Medical Record Verification for Pharmacies & Labs",
    verifyPrescription: "Verify Prescription",
    enterQrToken: "Enter QR Token / Prescription UUID",
    dispenseHelper: "Pharmacy Dispensing Checklist",
    markDispensed: "Dispensed",
    copyVerifyLink: "Copy Link",
    linkCopied: "Link Copied!",

    // Medical Report Vault
    medicalReportVault: "Medical Report Vault",
    medicalReportVaultSubtitle: "Upload and organize all diagnostic lab reports, blood tests, and scans.",
    uploadLabReport: "Upload Lab Report",
    diagnosticCenter: "Diagnostic Center",
    testDate: "Test Date",
    testCategory: "Test Category",
    summaryFindings: "Summary / Key Findings",
    documentUrl: "Document / Scan URL (PDF or Image)",
    viewDocument: "View Report Document ↗",
    noReportsFound: "No Medical Reports Uploaded Yet",
    noReportsHint: "Upload your blood tests, USGs, and diagnostic reports to access them anywhere.",

    // Homepage
    heroBadge: "Modernizing Clinic Operations & Care",
    heroPlatformBadge: "v2.4 Platform",
    heroTitle1: "Manage Clinics.",
    heroTitle2: "Book Appointments.",
    heroTitle3: "All in One Place.",
    heroSubtitle: "Smart Clinic connects clinic owners and patients through a simple, secure, and modern healthcare platform.",
    openYourClinic: "Open Your Clinic",
    findClinic: "Find a Clinic",
    onlineBookingBadge: "Online Booking",
    secureDataBadge: "Encrypted Health Data",
    uptimeBadge: "Cloud-Powered High Availability",
    trustedByPractitioners: "Trusted by registered medical practitioners in Bangladesh",
    quickBook: "Quick Book",
    everythingYouNeed: "Everything You Need",
    everythingYouNeedSubtitle: "Powerful tools for clinics and patients.",
    chooseYourJourney: "Choose Your Journey",
    chooseYourJourneySubtitle: "Tailored portals for healthcare providers and individuals seeking care.",
    clinicOwner: "Clinic Owner",
    clinicOwnerDesc: "Scale clinical workflows, doctor rosters, and digital billing from a unified console.",
    patient: "Patient",
    patientDesc: "Discover trusted doctors, schedule visits with zero waiting time, and access records.",
    openClinicBtn: "Open Clinic",
    becomePatientBtn: "Become Patient",
    forProviders: "For Providers",
    forPatients: "For Patients",
    readyToModernize: "Ready to Modernize Healthcare?",
    readyToModernizeSubtitle: "Join Smart Clinic today. Transform how your clinic operates and how patients book care.",
    getStarted: "Get Started",
    requestDemo: "Explore Clinics",
    noCardRequired: "No credit card required",
    freeTrial: "14-day free trial",
    hipaaCompliant: "Encrypted & Secure Health Records",

    // Features Section Cards
    featuresBadge: "Features",
    featClinicMgmtTitle: "Clinic Management",
    featClinicMgmtDesc: "Manage your clinic operations efficiently from one place.",
    featClinicMgmtTag: "Multi-branch ready",
    featAppointmentsTitle: "Appointments",
    featAppointmentsDesc: "Easy online appointment booking for patients.",
    featAppointmentsTag: "Real-time calendar sync",
    featDoctorsTitle: "Doctors",
    featDoctorsDesc: "Manage doctor profiles, rosters & schedules.",
    featDoctorsTag: "Rosters & leaves",
    featPatientRecordsTitle: "Patient Records",
    featPatientRecordsDesc: "Secure digital medical history & prescriptions.",
    featPatientRecordsTag: "EMR / E-Prescriptions",
    featNotificationsTitle: "Notifications",
    featNotificationsDesc: "Automatic appointment & queue reminders.",
    featNotificationsTag: "SMS & Email alerts",
    featSecureTitle: "Secure",
    featSecureDesc: "Protected with JWT authentication & encryption.",
    featSecureTag: "256-bit encryption",

    // RoleSection
    dualPortalsBadge: "Dual Portals",
    clinicFeature1: "Register Clinic",
    clinicFeature2: "Manage Doctors",
    clinicFeature3: "View Patients",
    clinicFeature4: "Appointment Dashboard",
    clinicFeature5: "Revenue & Schedule Analytics",

    // Clinics Page
    clinicPageBadge: "8 Divisions Healthcare Network",
    clinicPageTitle: "Find Top Clinics Near You",
    clinicPageSubtitle: "Browse verified multi-specialty hospitals and medical centers across all 8 divisions of Bangladesh. Compare doctor rosters and book instant serials.",
    clinicSearchPlaceholder: "Search by city or clinic name (e.g. Dhaka, Sylhet, Chattogram)...",
    clinicSearchBtn: "Search Clinics",
    clinicFilterLabel: "Filter by Division / Region:",
    clinicDivisionAll: "All",
    clinicShowingCount: "Showing",
    clinicVerifiedCenters: "verified medical centers",
    clinicVerifiedCentersIn: "in",
    clinicViewAllDoctors: "View All Doctors",
    clinicVerified: "Verified",
    clinicSpecializedDepts: "Specialized Departments",
    clinicMore: "more",
    clinicViewDetails: "View Details & Doctors",
    clinicNotFound: "No Clinics Found",
    clinicNotFoundMsg: "No partner centers found matching",
    clinicResetFilters: "Reset All Filters",
    clinicNewBadge: "New",
    clinicReviews: "reviews",
    clinicNoRating: "No ratings yet",
    clinicNearYou: "Clinics Near You",
    clinicNearYouSub: "Suggested based on your current location",
    clinicAllTitle: "All Clinics in Bangladesh",
    clinicAllSub: "Book from anywhere across all 8 divisions",
    clinicAwayKm: "km away",
    clinicLocationDetecting: "Detecting your location...",
    clinicLocationDenied: "Location access denied. Showing all clinics.",
    clinicUseLocation: "Use My Location",

    // Doctors Page
    doctorPageBadge: "Qualified Specialists",
    doctorPageTitle: "Find & Consult Expert Doctors",
    doctorPageSubtitle: "Connect with top-rated medical specialists across multiple disciplines and book your consultation in seconds.",
    doctorAllSpecs: "All Specializations",
    doctorShowingCount: "Showing",
    doctorRegisteredSpecs: "registered medical specialists",
    doctorViewClinics: "View All Partner Clinics",
    doctorNotFound: "No Doctors Found",
    doctorNotFoundMsg: "Try selecting a different specialization filter.",
    doctorYrsExp: "yrs exp",
    doctorNoReviews: "No reviews yet",
    doctorPracticingClinics: "Practicing Clinics:",
    doctorFee: "Fee:",
    doctorViewProfile: "View Profile",
    doctorBookBtn: "Book Appointment",

    // Login Page
    loginHeroTitle: "One Unified Sign-In for Everyone",
    loginHeroSubtitle: "Whether you are a Patient checking live queue numbers, a Doctor managing chamber consultations, or Clinic Staff settling daily counter cash.",
    loginLiveStatus: "Live System Active",
    loginFeature1: "Sign in with Email or Phone Number",
    loginFeature2: "Real-time Live Queue Tracker with Audio Chime",
    loginFeature3: "Encrypted Health Records & Verified EMR",
    loginPrivacyLink: "Privacy & Data Policy",
    loginTitle: "Log In to Smart Clinic",
    loginSubtitle: "Enter your email address or phone number and password to continue.",
    loginEmailLabel: "Email Address or Mobile Number",
    loginEmailPlaceholder: "Email or phone number",
    loginPasswordLabel: "Password",
    loginPasswordPlaceholder: "Password",
    loginRememberMe: "Remember me",
    loginForgotPassword: "Forgot password?",
    loginForgotHint: "Forgot your password?",
    loginForgotReset: "Reset it here",
    loginBtn: "Log In",
    loginLoading: "Signing in...",
    loginOr: "or",
    loginCreateAccount: "Create New Account",
    loginErrorEmpty: "Please enter your email or phone number and password.",
    loginErrorInvalid: "Invalid email/phone or password. Please try again.",

    // Register Page
    registerTitle: "Create Your Account",
    registerSubtitle: "Join Smart Clinic as a Patient, Doctor, or Clinic Admin",
    registerDoctorProfileTitle: "Complete Your Doctor Profile",
    registerDoctorProfileSubtitle: "Set up your professional profile so patients can find and book with you",
    registerStep1: "Account",
    registerStep2: "Doctor Profile",
    registerFirstName: "First Name",
    registerLastName: "Last Name",
    registerEmail: "Email Address",
    registerPhone: "Phone Number",
    registerPhoneHint: "Bangladeshi 11-digit mobile number (e.g. 01712345678)",
    registerRoleLabel: "Register As",
    registerRolePatient: "Patient",
    registerRolePatientDesc: "Book appointments & consult doctors",
    registerRoleDoctor: "Doctor",
    registerRoleDoctorDesc: "Register & manage your consultations",
    registerRoleClinicAdmin: "Clinic Admin",
    registerRoleClinicAdminDesc: "Create & manage your clinic",
    registerPassword: "Password",
    registerConfirmPassword: "Confirm Password",
    registerPasswordPlaceholder: "Min 8 chars",
    registerConfirmPasswordPlaceholder: "Repeat password",
    registerSubmitBtn: "Create Account",
    registerContinueDoctorBtn: "Continue to Profile Setup",
    registerAlreadyHaveAccount: "Already have an account?",
    registerSignInHere: "Sign in here",
    registerSuccessPatient: "Account created successfully! Redirecting...",
    registerSuccessClinic: "Account created! Redirecting to Clinic Setup...",
    registerDoctorFullName: "Full Name (as it appears to patients)",
    registerDoctorQualification: "Qualification",
    registerDoctorExperience: "Years of Experience",
    registerDoctorBio: "Bio / Professional Summary",
    registerDoctorBioPlaceholder: "Brief description of your expertise and approach to patient care...",
    registerDoctorCertificate: "Medical License / Certificate URL *",
    registerDoctorCertificateHint: "Admin will verify your certificate before approving your profile.",
    registerDoctorSpecializations: "Specializations (select all that apply)",
    registerDoctorCompleteBtn: "Complete Registration",
    registerBackBtn: "Back",

    // Doctor Detail Page
    docDetailVerified: "Verified Specialist",
    docDetailYearsExp: "Years Experience",
    docDetailReviews: "reviews",
    docDetailCert: "Medical Registration Certificate",
    docDetailAbout: "About",
    docDetailClinicsTitle: "Practicing Clinics & Chambers",
    docDetailNoClinics: "No clinics currently mapped to this doctor.",
    docDetailFee: "Consultation Fee",
    docDetailViewClinic: "View Clinic",
    docDetailBookHere: "Book Here",
    docDetailVerifiedReviews: "Verified Patient Reviews",
    docDetailReviewsSub: "Ratings and genuine feedback from patients treated by",
    docDetailNoReviewsYet: "No reviews yet for",
    docDetailNoReviewsSub: "Reviews appear after patients complete their chamber consultation.",
    docDetailAllDoctors: "All Doctors",
    docDetailReturnDashboard: "Return to Dashboard",
    docDetailBack: "Back",

    // Clinic Detail Page
    clinicDetailBack: "Back",
    clinicDetailReturnDashboard: "Return to Dashboard",
    clinicDetailAllClinics: "All Clinics",
    clinicDetailPracticingDoctors: "Practicing Doctors",
    clinicDetailNoDoctors: "No active doctors currently mapped to this clinic.",
    clinicDetailBookAppointment: "Book Appointment",
    clinicDetailReviews: "Verified Patient Reviews",
    clinicDetailReviewsSub: "Honest ratings and feedback submitted by patients after completing visits.",
    clinicDetailNoReviews: "No patient reviews yet for this clinic",
    clinicDetailNoReviewsSub: "Reviews appear automatically after verified patients complete their consultations.",
    clinicDetailServicesTitle: "Clinical Services & Diagnostic Tests",
    clinicDetailServicesSub: "In-house lab tests, imaging, investigations, and healthcare services offered at this clinic.",
    clinicDetailSearchService: "Search test or service...",
    clinicDetailNoServicesMatch: "No services match",
    clinicDetailGalleryTitle: "Clinic Facilities & Diagnostic Infrastructure",
    clinicDetailGallerySub: "Take a visual walkthrough of our examination rooms, labs, waiting lounges, and equipment.",
    clinicDetailFullscreen: "View Fullscreen",
    clinicDetailVerifiedInClinic: "Verified In-Clinic",
    clinicDetailExplore: "Explore",

    patientFeature1: "Find Clinics",
    patientFeature2: "Book Appointment",
    patientFeature3: "Appointment History",
    patientFeature4: "Digital Records",
    patientFeature5: "Instant SMS Confirmations",

    // Standard Healthcare Operations Terminology
    callNextSerial: "Call Next Serial",
    currentSerial: "Current Serial",
    liveQueue: "Live Queue",
    printToken: "Print Token",
    reception: "Reception Desk",
    chamber: "Doctor Chamber",
    break: "Break",
    paused: "Paused",
    sessionEnded: "Session Ended",
    emergency: "Emergency",
    onHold: "On Hold",
    skipped: "Skipped",
    recall: "Recall",

    // Clinic Admin Dashboard
    quickShortcuts: "Quick Reception Shortcuts",
    quickShortcutsHint: "1-Click Direct Actions",
    newWalkIn: "New Walk-in",
    newWalkInSub: "Counter Registration & Serial",
    waitingRoomTv: "Waiting Room TV",
    waitingRoomTvSub: "Lobby Display Screen",
    dailyCashAudit: "Daily Cash Audit",
    dailyCashAuditSub: "Accounts & Audit Sheet",
    inviteDoctor: "Invite Doctor",
    inviteDoctorSub: "Add Affiliated Doctor",
    weeklyTrendSubtitle: "Last 7 days bookings & completed visits",
    monthlyTrendSubtitle: "Last 30 days daily trend (Rise & Fall)",
    trendHoverHint: "💡 Hover over any point to view daily patient details",
    rise: "Rise",
    fall: "Fall",
    announcementsTitle: "Clinic Announcements & Public Notices",
    walkInModalTitle: "Walk-in Counter Registration",
    cashAtCounterInstant: "Cash at Counter (Verified & Auto-Settled)",
  },

  bn: {
    // Nav
    home: "হোম",
    doctors: "ডাক্তার",
    clinics: "ক্লিনিক",
    bookAppointment: "অ্যাপয়েন্টমেন্ট করুন",
    dashboard: "ড্যাশবোর্ড",
    signIn: "লগইন করুন",
    signUp: "নিবন্ধন করুন",
    signOut: "লগআউট",
    notifications: "বিজ্ঞপ্তি",
    noNotifications: "কোনো নতুন বিজ্ঞপ্তি নেই",

    // Navigation & Workspace
    accountSettings: "অ্যাকাউন্ট সেটিংস",
    clinicalWorkspace: "ক্লিনিক্যাল চেম্বার",
    clinical: "চেম্বার",
    clinicAffiliations: "ক্লিনিক অন্তর্ভুক্তি",
    affiliations: "অন্তর্ভুক্তি",
    chamberSchedule: "চেম্বার সময়সূচী",
    schedule: "সময়সূচী",
    doctorCredentials: "যোগ্যতা ও সনদ",
    credentials: "সনদ",
    erxAndVitals: "ই-প্রেসক্রিপশন ও ভাইটালস",
    medicalReports: "রিপোর্ট",
    chamberQueue: "সিরিয়াল কিউ",

    // Reception Desk
    receptionist_console: "অভ্যর্থনা ডেস্ক কনসোল",

    // Patient Dashboard
    patientDashboard: "রোগীর ড্যাশবোর্ড",
    patientDashboardSubtitle: "লাইভ সিরিয়াল ট্র্যাকার, অ্যাপয়েন্টমেন্ট ও পারিবারিক স্বাস্থ্যসেবা",
    myAppointments: "আমার অ্যাপয়েন্টমেন্ট",
    familyProfiles: "পরিবার প্রোফাইল",
    addFamilyMember: "পরিবারের সদস্য যোগ করুন",
    noAppointments: "কোনো অ্যাপয়েন্টমেন্ট নেই",
    noAppointmentsHint: "আপনি এখনো কোনো ডাক্তারের সাথে পরামর্শ নেননি।",
    bookNow: "এখনই অ্যাপয়েন্টমেন্ট করুন",

    // Serial Tracker
    liveSerialTracker: "লাইভ সিরিয়াল ট্র্যাকার",
    doctorStatus: "ডাক্তারের অবস্থা:",
    refreshesAuto: "স্বয়ংক্রিয়ভাবে রিফ্রেশ হচ্ছে ⏱️",
    currentlyCalled: "বর্তমানে ডাকা হচ্ছে",
    yourSerial: "আপনার সিরিয়াল #",
    patientsAhead: "সামনে রোগী",
    estWait: "অনুমানিত অপেক্ষা",
    yourTurn: "আপনার পালা!",
    itsYourTurn: "🎉 এখন আপনার পালা! ডা.",
    consultationRoom: "-এর চেম্বারে প্রবেশ করুন।",
    getReady: "🔔 প্রস্তুত থাকুন: আর মাত্র",
    patientsAway: "জন রোগী বাকি! অনুগ্রহ করে ওয়েটিং লাউঞ্জে রিপোর্ট করুন।",

    // Appointment card
    serialBadge: "সিরিয়াল #",
    forPatient: "রোগী:",
    pendingPayment: "পেমেন্ট বাকি",
    confirmed: "নিশ্চিত",
    completed: "সম্পন্ন",
    cancelled: "বাতিল",
    payAndConfirm: "পেমেন্ট করুন ও নিশ্চিত করুন",
    cancel: "বাতিল করুন",
    viewPrescription: "ই-প্রেসক্রিপশন দেখুন",
    leaveReview: "রিভিউ দিন",

    // Payment
    processPayment: "পেমেন্ট প্রক্রিয়া করুন",
    amountPayable: "প্রদেয় পরিমাণ",
    selectPaymentMethod: "পেমেন্ট পদ্ধতি বেছে নিন",
    enterTrxId: "ট্রানজেকশন আইডি (TrxID) দিন *",
    cashAtChamberNote: "ক্লিনিক কাউন্টারে নগদ: ক্লিনিক রিসেপশন নগদ পেমেন্ট নিশ্চিত না করা পর্যন্ত আপনার অ্যাপয়েন্টমেন্ট পেমেন্ট-অপেক্ষমান থাকবে।",
    confirmPayment: "পেমেন্ট নিশ্চিত করুন",
    confirming: "নিশ্চিত হচ্ছে...",

    // Family
    parentCareTitle: "অভিভাবক সেবা ও পারিবারিক প্রোফাইল",
    parentCareSubtitle: "বাবা-মা, স্বামী/স্ত্রী বা সন্তানদের যোগ করুন এবং তাদের অ্যাপয়েন্টমেন্ট ও স্বাস্থ্য ইতিহাস পরিচালনা করুন।",
    addMember: "সদস্য যোগ করুন",
    noFamilyMembers: "কোনো পারিবারিক সদস্য যোগ করা হয়নি",
    noFamilyHint: "আপনার পরিবারের সদস্যদের যোগ করুন এবং সহজেই তাদের পক্ষে অ্যাপয়েন্টমেন্ট নিন।",
    fullName: "পুরো নাম",
    relationship: "সম্পর্ক",
    phone: "ফোন নম্বর (বাংলাদেশ)",
    age: "বয়স",
    dateOfBirth: "জন্ম তারিখ",
    gender: "লিঙ্গ",
    bloodGroup: "রক্তের গ্রুপ",
    medicalNotes: "চিকিৎসার নোট / ইতিহাস",
    saveMember: "সদস্য সংরক্ষণ করুন",
    editMember: "সদস্য সম্পাদনা করুন",
    updateMember: "আপডেট করুন",
    deleteMember: "মুছুন",
    confirmDeleteMember: "আপনি কি নিশ্চিতভাবে এই সদস্যকে মুছে ফেলতে চান?",
    saving: "সংরক্ষণ হচ্ছে...",

    // Prescription
    officialPrescription: "অফিসিয়াল ডিজিটাল ই-প্রেসক্রিপশন",
    printPdf: "প্রিন্ট / পিডিএফ",
    qrVerified: "QR যাচাইকৃত",
    scanToVerify: "যাচাই করতে স্ক্যান করুন",
    recommendedTests: "প্রস্তাবিত ল্যাব পরীক্ষা:",
    doctorAdvice: "ডাক্তারের পরামর্শ:",
    prescribedMedicines: "Rx (নির্ধারিত ওষুধ)",
    rxVerificationTitle: "অফিসিয়াল ই-প্রেসক্রিপশন যাচাইকরণ",
    rxVerificationSubtitle: "ফার্মেসি ও ডায়াগনস্টিক ল্যাবের জন্য ডিজিডিএ অনুমোদিত ডিজিটাল চিকিৎসা ব্যবস্থাপত্র যাচাইকরণ",
    verifyPrescription: "প্রেসক্রিপশন যাচাই করুন",
    enterQrToken: "কিউআর টোকেন বা কোড লিখুন",
    dispenseHelper: "ফার্মেসি ওষুধ বিতরণ চেকলিস্ট",
    markDispensed: "দেওয়া হয়েছে",
    copyVerifyLink: "লিংক কপি",
    linkCopied: "লিংক কপি হয়েছে!",

    // Medical Report Vault
    medicalReportVault: "মেডিকেল রিপোর্ট ভল্ট",
    medicalReportVaultSubtitle: "আপনার সব ডায়াগনস্টিক রিপোর্ট, রক্তের পরীক্ষা এবং স্ক্যান নিরাপদে সংরক্ষণ করুন।",
    uploadLabReport: "ল্যাব রিপোর্ট আপলোড করুন",
    diagnosticCenter: "ডায়াগনস্টিক সেন্টার",
    testDate: "পরীক্ষার তারিখ",
    testCategory: "পরীক্ষার ধরন",
    summaryFindings: "সারাংশ / প্রধান ফলাফল",
    documentUrl: "ডকুমেন্ট / স্ক্যান URL (পিডিএফ বা ছবি)",
    viewDocument: "রিপোর্ট ডকুমেন্ট দেখুন ↗",
    noReportsFound: "এখনো কোনো মেডিকেল রিপোর্ট আপলোড করা হয়নি",
    noReportsHint: "আপনার রক্তের পরীক্ষা, আল্ট্রাসনোগ্রাম এবং ডায়াগনস্টিক রিপোর্টগুলো আপলোড করে যেকোনো জায়গা থেকে অ্যাক্সেস করুন।",

    // Homepage
    heroBadge: "আধুনিক ক্লিনিক ও চিকিৎসা সেবা কার্যক্রম",
    heroPlatformBadge: "v২.৪ প্ল্যাটফর্ম",
    heroTitle1: "ক্লিনিক পরিচালনা করুন।",
    heroTitle2: "অ্যাপয়েন্টমেন্ট বুক করুন।",
    heroTitle3: "সবকিছু এক প্ল্যাটফর্মে।",
    heroSubtitle: "স্মার্ট ক্লিনিক ক্লিনিক মালিক ও রোগীদের একটি সহজ, নিরাপদ ও আধুনিক স্বাস্থ্যসেবা প্ল্যাটফর্মের মাধ্যমে যুক্ত করে।",
    openYourClinic: "ক্লিনিক চালু করুন",
    findClinic: "ক্লিনিক খুঁজুন",
    onlineBookingBadge: "অনলাইন বুকিং",
    secureDataBadge: "নিরাপদ ও এনক্রিপ্টেড ডাটা",
    uptimeBadge: "উচ্চগতির ক্লাউড সেবা",
    trustedByPractitioners: "বাংলাদেশের নিবন্ধিত চিকিৎসকদের জন্য তৈরি",
    quickBook: "দ্রুত বুক করুন",
    everythingYouNeed: "আপনার প্রয়োজনীয় সবকিছু",
    everythingYouNeedSubtitle: "ক্লিনিক এবং রোগীদের জন্য আধুনিক সব টুলস।",
    chooseYourJourney: "আপনার মাধ্যম বেছে নিন",
    chooseYourJourneySubtitle: "স্বাস্থ্যসেবা প্রদানকারী এবং সেবা গ্রহীতাদের জন্য সুনির্দিষ্ট পোর্টাল।",
    clinicOwner: "ক্লিনিক মালিক",
    clinicOwnerDesc: "ক্লিনিক্যাল কার্যপ্রবাহ, ডাক্তারদের রোস্টার এবং ডিজিটাল বিলিং পরিচালনা করুন এক কনসোল থেকে।",
    patient: "রোগী",
    patientDesc: "বিশ্বস্ত ডাক্তার খুঁজুন, কোনো বিলম্ব ছাড়াই ভিজিট শিডিউল করুন এবং প্রেসক্রিপশন পান।",
    openClinicBtn: "ক্লিনিক খুলুন",
    becomePatientBtn: "রোগী হিসেবে যুক্ত হন",
    forProviders: "সেবা প্রদানকারীদের জন্য",
    forPatients: "রোগীদের জন্য",
    readyToModernize: "স্বাস্থ্যসেবায় আধুনিক হতে প্রস্তুত?",
    readyToModernizeSubtitle: "আজই স্মার্ট ক্লিনিকে যোগ দিন। আপনার ক্লিনিক কার্যক্রম রূপান্তর করুন।",
    getStarted: "শুরু করুন",
    requestDemo: "ক্লিনিক দেখুন",
    noCardRequired: "কোনো ক্রেডিট কার্ড লাগবে না",
    freeTrial: "১৪ দিনের ফ্রি ট্রায়াল",
    hipaaCompliant: "সুরক্ষিত ও এনক্রিপ্টেড স্বাস্থ্য তথ্য",

    // Features Section Cards
    featuresBadge: "বৈশিষ্ট্যসমূহ",
    featClinicMgmtTitle: "ক্লিনিক ব্যবস্থাপনা",
    featClinicMgmtDesc: "এক জায়গা থেকে দক্ষতার সাথে ক্লিনিক পরিচালনা করুন।",
    featClinicMgmtTag: "মাল্টি-শাখা প্রস্তুত",
    featAppointmentsTitle: "অ্যাপয়েন্টমেন্ট",
    featAppointmentsDesc: "রোগীদের জন্য সহজে অনলাইনে বুকিং করুন।",
    featAppointmentsTag: "রিয়েল-টাইম ক্যালেন্ডার",
    featDoctorsTitle: "ডাক্তার",
    featDoctorsDesc: "ডাক্তারের প্রোফাইল, রোস্টার ও সময়সূচী পরিচালনা করুন।",
    featDoctorsTag: "রোস্টার ও ছুটি",
    featPatientRecordsTitle: "রোগীর রেকর্ড",
    featPatientRecordsDesc: "নিরাপদ ডিজিটাল চিকিৎসা ইতিহাস ও প্রেসক্রিপশন।",
    featPatientRecordsTag: "ই-প্রেসক্রিপশন",
    featNotificationsTitle: "বিজ্ঞপ্তি",
    featNotificationsDesc: "স্বয়ংক্রিয় অ্যাপয়েন্টমেন্ট ও কিউ রিমাইন্ডার।",
    featNotificationsTag: "SMS ও ইমেইল",
    featSecureTitle: "নিরাপত্তা",
    featSecureDesc: "JWT অথেনটিকেশন ও এনক্রিপশনে সুরক্ষিত।",
    featSecureTag: "২৫৬-বিট এনক্রিপশন",

    // RoleSection
    dualPortalsBadge: "দুটি পোর্টাল",
    clinicFeature1: "ক্লিনিক নিবন্ধন করুন",
    clinicFeature2: "ডাক্তার পরিচালনা করুন",
    clinicFeature3: "রোগী ব্যবস্থাপনা করুন",
    clinicFeature4: "অ্যাপয়েন্টমেন্ট ড্যাশবোর্ড",
    clinicFeature5: "রাজস্ব ও শিডিউল বিশ্লেষণ",

    // Clinics Page
    clinicPageBadge: "৮ বিভাগ স্বাস্থ্যসেবা নেটওয়ার্ক",
    clinicPageTitle: "আপনার কাছের সেরা ক্লিনিক খুঁজুন",
    clinicPageSubtitle: "বাংলাদেশের সকল ৮ বিভাগে যাচাইকৃত হাসপাতাল ও মেডিকেল সেন্টার খুঁজুন। ডাক্তার রোস্টার তুলনা করুন এবং তাৎক্ষণিক সিরিয়াল নিন।",
    clinicSearchPlaceholder: "শহর বা ক্লিনিকের নাম লিখুন যেমন: ঢাকা, সিলেট, চট্টগ্রাম...",
    clinicSearchBtn: "ক্লিনিক খুঁজুন",
    clinicFilterLabel: "বিভাগ অনুযায়ী ফিল্টার করুন:",
    clinicDivisionAll: "সকল",
    clinicShowingCount: "পাওয়া গেছে",
    clinicVerifiedCenters: "টি যাচাইকৃত মেডিকেল সেন্টার",
    clinicVerifiedCentersIn: "এ",
    clinicViewAllDoctors: "সকল ডাক্তার দেখুন",
    clinicVerified: "যাচাইকৃত",
    clinicSpecializedDepts: "বিশেষজ্ঞ বিভাগ",
    clinicMore: "আরও",
    clinicViewDetails: "বিস্তারিত দেখুন",
    clinicNotFound: "কোনো ক্লিনিক পাওয়া যায়নি",
    clinicNotFoundMsg: "এই নামে কোনো পার্টনার সেন্টার পাওয়া যায়নি",
    clinicResetFilters: "সকল ফিল্টার রিসেট করুন",
    clinicNewBadge: "নতুন",
    clinicReviews: "রিভিউ",
    clinicNoRating: "এখনো কোনো রেটিং নেই",
    clinicNearYou: "আপনার কাছের ক্লিনিক",
    clinicNearYouSub: "আপনার বর্তমান অবস্থানের উপর ভিত্তি করে সাজেস্ট করা হয়েছে",
    clinicAllTitle: "বাংলাদেশের সকল ক্লিনিক",
    clinicAllSub: "সকল ৮ বিভাগ থেকে যেকোনো ক্লিনিকে অ্যাপয়েন্টমেন্ট নিন",
    clinicAwayKm: "কিমি দূরে",
    clinicLocationDetecting: "আপনার অবস্থান শনাক্ত হচ্ছে...",
    clinicLocationDenied: "অবস্থান অ্যাক্সেস প্রত্যাখ্যান করা হয়েছে। সকল ক্লিনিক দেখানো হচ্ছে।",
    clinicUseLocation: "আমার অবস্থান ব্যবহার করুন",

    // Doctors Page
    doctorPageBadge: "যোগ্য বিশেষজ্ঞ",
    doctorPageTitle: "বিশেষজ্ঞ ডাক্তার খুঁজুন ও পরামর্শ নিন",
    doctorPageSubtitle: "বিভিন্ন বিশেষত্বের শীর্ষ রেটেড বিশেষজ্ঞ ডাক্তারদের সাথে যোগাযোগ করুন এবং মুহূর্তের মধ্যে পরামর্শ বুক করুন।",
    doctorAllSpecs: "সব বিশেষত্ব",
    doctorShowingCount: "পাওয়া গেছে",
    doctorRegisteredSpecs: "জন নিবন্ধিত বিশেষজ্ঞ",
    doctorViewClinics: "সব পার্টনার ক্লিনিক দেখুন",
    doctorNotFound: "কোনো ডাক্তার পাওয়া যায়নি",
    doctorNotFoundMsg: "অন্য একটি বিশেষত্ব ফিল্টার নির্বাচন করে দেখুন।",
    doctorYrsExp: "বছরের অভিজ্ঞতা",
    doctorNoReviews: "এখনো কোনো রিভিউ নেই",
    doctorPracticingClinics: "কর্মরত ক্লিনিক:",
    doctorFee: "ফি:",
    doctorViewProfile: "প্রোফাইল দেখুন",
    doctorBookBtn: "অ্যাপয়েন্টমেন্ট নিন",

    // Login Page
    loginHeroTitle: "সবার জন্য একটি সমন্বিত লগ ইন",
    loginHeroSubtitle: "আপনি রোগী হোন, লাইভ কিউ দেখুন, ডাক্তার হিসেবে চেম্বার পরিচালনা করুন, বা ক্লিনিক স্টাফ হিসেবে দৈনিক কাউন্টার সামলান।",
    loginLiveStatus: "সিস্টেম সক্রিয়",
    loginFeature1: "ইমেইল বা ফোন নম্বর দিয়ে লগ ইন করুন",
    loginFeature2: "অডিও চাইম সহ রিয়েল-টাইম লাইভ কিউ ট্র্যাকার",
    loginFeature3: "এনক্রিপ্টেড স্বাস্থ্য রেকর্ড ও যাচাইকৃত EMR",
    loginPrivacyLink: "গোপনীয়তা ও ডেটা নীতি",
    loginTitle: "স্মার্ট ক্লিনিকে লগ ইন করুন",
    loginSubtitle: "চালিয়ে যেতে আপনার ইমেইল বা ফোন নম্বর এবং পাসওয়ার্ড দিন।",
    loginEmailLabel: "ইমেইল বা মোবাইল নম্বর",
    loginEmailPlaceholder: "ইমেইল বা ফোন নম্বর",
    loginPasswordLabel: "পাসওয়ার্ড",
    loginPasswordPlaceholder: "পাসওয়ার্ড",
    loginRememberMe: "আমাকে মনে রাখুন",
    loginForgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    loginForgotHint: "পাসওয়ার্ড ভুলে গেছেন?",
    loginForgotReset: "এখানে রিসেট করুন",
    loginBtn: "লগ ইন",
    loginLoading: "লগ ইন হচ্ছে...",
    loginOr: "অথবা",
    loginCreateAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
    loginErrorEmpty: "অনুগ্রহ করে আপনার ইমেইল বা ফোন নম্বর এবং পাসওয়ার্ড দিন।",
    loginErrorInvalid: "ভুল ইমেইল/ফোন বা পাসওয়ার্ড। আবার চেষ্টা করুন।",

    // Register Page
    registerTitle: "আপনার অ্যাকাউন্ট তৈরি করুন",
    registerSubtitle: "রোগী, ডাক্তার বা ক্লিনিক অ্যাডমিন হিসেবে স্মার্ট ক্লিনিকে যোগ দিন",
    registerDoctorProfileTitle: "ডাক্তার প্রোফাইল সম্পূর্ণ করুন",
    registerDoctorProfileSubtitle: "রোগীরা যাতে আপনাকে সহজে খুঁজে পায় এবং বুক করতে পারে সেজন্য পেশাদার প্রোফাইল সেট আপ করুন",
    registerStep1: "অ্যাকাউন্ট",
    registerStep2: "ডাক্তার প্রোফাইল",
    registerFirstName: "নামের প্রথম অংশ",
    registerLastName: "নামের শেষ অংশ",
    registerEmail: "ইমেইল ঠিকানা",
    registerPhone: "ফোন নম্বর",
    registerPhoneHint: "১১ ডিজিটের বাংলাদেশি মোবাইল নম্বর (যেমন: 01712345678)",
    registerRoleLabel: "যে হিসেবে নিবন্ধন করবেন",
    registerRolePatient: "রোগী",
    registerRolePatientDesc: "অ্যাপয়েন্টমেন্ট নিন ও ডাক্তারের পরামর্শ নিন",
    registerRoleDoctor: "ডাক্তার",
    registerRoleDoctorDesc: "নিবন্ধন করুন ও চেম্বার পরামর্শ পরিচালনা করুন",
    registerRoleClinicAdmin: "ক্লিনিক অ্যাডমিন",
    registerRoleClinicAdminDesc: "আপনার ক্লিনিক তৈরি ও পরিচালনা করুন",
    registerPassword: "পাসওয়ার্ড",
    registerConfirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    registerPasswordPlaceholder: "কমপক্ষে ৮ অক্ষর",
    registerConfirmPasswordPlaceholder: "পুনরায় পাসওয়ার্ড দিন",
    registerSubmitBtn: "অ্যাকাউন্ট তৈরি করুন",
    registerContinueDoctorBtn: "প্রোফাইল সেটআপে এগিয়ে যান",
    registerAlreadyHaveAccount: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    registerSignInHere: "এখানে লগ ইন করুন",
    registerSuccessPatient: "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে! পুনঃনির্দেশ করা হচ্ছে...",
    registerSuccessClinic: "অ্যাকাউন্ট তৈরি হয়েছে! ক্লিনিক সেটআপে পাঠানো হচ্ছে...",
    registerDoctorFullName: "পূর্ণ নাম (রোগীদের যা দেখানো হবে)",
    registerDoctorQualification: "শিক্ষাগত যোগ্যতা",
    registerDoctorExperience: "অভিজ্ঞতার বছর",
    registerDoctorBio: "জীবনবৃত্তান্ত / সারসংক্ষেপ",
    registerDoctorBioPlaceholder: "আপনার কাজের অভিজ্ঞতা এবং চিকিৎসা পদ্ধতি সম্পর্কে সংক্ষেপে লিখুন...",
    registerDoctorCertificate: "মেডিকেল লাইসেন্স / সনদের লিংক *",
    registerDoctorCertificateHint: "প্রোফাইল অনুমোদনের আগে অ্যাডমিন আপনার সনদপত্র যাচাই করবে।",
    registerDoctorSpecializations: "বিশেষত্ব (প্রযোজ্য সবগুলো নির্বাচন করুন)",
    registerDoctorCompleteBtn: "নিবন্ধন সম্পন্ন করুন",
    registerBackBtn: "ফিরে যান",

    // Doctor Detail Page
    docDetailVerified: "যাচাইকৃত বিশেষজ্ঞ",
    docDetailYearsExp: "বছরের অভিজ্ঞতা",
    docDetailReviews: "রিভিউ",
    docDetailCert: "মেডিকেল রেজিস্ট্রেশন সনদ",
    docDetailAbout: "পরিচিতি ও বিবরণ",
    docDetailClinicsTitle: "কর্মরত ক্লিনিক ও চেম্বার",
    docDetailNoClinics: "বর্তমানে এই ডাক্তারের সাথে কোনো ক্লিনিক সংযুক্ত নেই।",
    docDetailFee: "পরামর্শ ফি",
    docDetailViewClinic: "ক্লিনিক দেখুন",
    docDetailBookHere: "এখানে বুক করুন",
    docDetailVerifiedReviews: "রোগীদের যাচাইকৃত রিভিউ",
    docDetailReviewsSub: "পরামর্শ নেওয়া রোগীদের প্রকৃত মতামত ও রেটিং",
    docDetailNoReviewsYet: "এখনো কোনো রিভিউ নেই",
    docDetailNoReviewsSub: "রোগীরা চেম্বার পরামর্শ সম্পন্ন করার পর রিভিউ দেখা যাবে।",
    docDetailAllDoctors: "সকল ডাক্তার",
    docDetailReturnDashboard: "ড্যাশবোর্ডে ফিরুন",
    docDetailBack: "ফিরে যান",

    // Clinic Detail Page
    clinicDetailBack: "ফিরে যান",
    clinicDetailReturnDashboard: "ড্যাশবোর্ডে ফিরুন",
    clinicDetailAllClinics: "সকল ক্লিনিক",
    clinicDetailPracticingDoctors: "কর্মরত ডাক্তারগণ",
    clinicDetailNoDoctors: "বর্তমানে এই ক্লিনিকে কোনো সক্রিয় ডাক্তার সংযুক্ত নেই।",
    clinicDetailBookAppointment: "অ্যাপয়েন্টমেন্ট নিন",
    clinicDetailReviews: "রোগীদের যাচাইকৃত রিভিউ",
    clinicDetailReviewsSub: "সরাসরি চিকিৎসা নেওয়া রোগীদের প্রকৃত মতামত ও রেটিং।",
    clinicDetailNoReviews: "এই ক্লিনিকের জন্য এখনো কোনো রিভিউ নেই",
    clinicDetailNoReviewsSub: "রোগীরা চিকিৎসা সম্পন্ন করার পর রিভিউ দেখা যাবে।",
    clinicDetailServicesTitle: "ক্লিনিক্যাল সেবা ও টেস্টসমূহ",
    clinicDetailServicesSub: "এই ক্লিনিকে উপলব্ধ ল্যাব টেস্ট, ইমেজিং এবং অন্যান্য স্বাস্থ্যসেবা।",
    clinicDetailSearchService: "টেস্ট বা সেবা খুঁজুন...",
    clinicDetailNoServicesMatch: "কোনো সেবা পাওয়া যায়নি",
    clinicDetailGalleryTitle: "ক্লিনিকের অবকাঠামো ও সুযোগ-সুবিধা",
    clinicDetailGallerySub: "আমাদের চেম্বার রুম, ল্যাব এবং ওয়েটিং লাউঞ্জের এক ঝলক।",
    clinicDetailFullscreen: "পূর্ণ পর্দা দেখুন",
    clinicDetailVerifiedInClinic: "ক্লিনিকে যাচাইকৃত",
    clinicDetailExplore: "দেখুন",

    patientFeature1: "ক্লিনিক খুঁজুন",
    patientFeature2: "অ্যাপয়েন্টমেন্ট বুক করুন",
    patientFeature3: "বুকিং ইতিহাস দেখুন",
    patientFeature4: "ডিজিটাল রেকর্ড",
    patientFeature5: "তাৎক্ষণিক SMS নিশ্চিতকরণ",

    // Standard Healthcare Operations Terminology
    callNextSerial: "পরবর্তী সিরিয়াল ডাকুন",
    currentSerial: "বর্তমান সিরিয়াল",
    liveQueue: "লাইভ সিরিয়াল",
    printToken: "টোকেন প্রিন্ট",
    reception: "রিসেপশন কাউন্টার",
    chamber: "ডাক্তার চেম্বার",
    break: "বিরতি",
    paused: "স্থগিত",
    sessionEnded: "চেম্বার শেষ",
    emergency: "জরুরি রোগী",
    onHold: "সাময়িক বিরতি",
    skipped: "স্কিপ করা",
    recall: "পুনরায় ডাকুন",

    // Clinic Admin Dashboard
    quickShortcuts: "দ্রুত অভ্যর্থনা শর্টকাট",
    quickShortcutsHint: "১-ক্লিকে সরাসরি কাজ করুন",
    newWalkIn: "নতুন ওয়াক-ইন",
    newWalkInSub: "কাউন্টার সিরিয়াল ও নিবন্ধন",
    waitingRoomTv: "ওয়েটিং রুম টিভি",
    waitingRoomTvSub: "লবি ডিসপ্লে স্ক্রিন",
    dailyCashAudit: "দৈনিক ক্যাশ অডিট",
    dailyCashAuditSub: "হিসাব ও অডিট শিট",
    inviteDoctor: "ডাক্তার যুক্ত করুন",
    inviteDoctorSub: "নতুন ডাক্তার আমন্ত্রণ",
    weeklyTrendSubtitle: "গত ৭ দিনের বুকিং ও সম্পন্ন ভিজিট",
    monthlyTrendSubtitle: "গত ৩০ দিনের দৈনিক ওঠানামার ট্রেন্ড",
    trendHoverHint: "💡 পয়েন্টের উপর মাউস রেখে যে কোনো দিনের রোগীর ওঠানামা দেখুন",
    rise: "বৃদ্ধি",
    fall: "হ্রাস",
    announcementsTitle: "ক্লিনিক নোটিশ ও সাধারণ ঘোষণা",
    walkInModalTitle: "ওয়াক-ইন কাউন্টার রেজিস্ট্রেশন",
    cashAtCounterInstant: "কাউন্টার ক্যাশ (স্বয়ংক্রিয় পরিশোধিত)",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("sc_lang") || "en"
  );

  const toggleLanguage = () => {
    const next = language === "en" ? "bn" : "en";
    setLanguage(next);
    localStorage.setItem("sc_lang", next);
  };

  const t = (key) => translations[language]?.[key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside <LanguageProvider>");
  return ctx;
}
