# Generated by Django 5.0.14 on 2026-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('SERIAL_PROXIMITY_ALERT', 'Serial Proximity Alert'), ('PRESCRIPTION_ISSUED', 'Prescription Issued'), ('CLINIC_APPROVED', 'Clinic Approved'), ('DOCTOR_APPROVED', 'Doctor Approved'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
    ]
