# Generated by Django 5.0.14 on 2026-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of clinic registration certificate', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
