# Generated by Django 5.0.14 on 2026-09-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_certificate_url_clinic_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicdepartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clinic Department', 'verbose_name_plural': 'Clinic Departments'},
        ),
    ]
