# Generated by Django 5.0.14 on 2026-09-12 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinicdepartment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, default='', help_text='About the clinic, overview and patient care mission'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', help_text='Emergency hotline number', max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities/facilities e.g. 24/7 Emergency, Pharmacy, Parking'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_hours',
            field=models.CharField(blank=True, default='Open 24/7', help_text='Operating hours display', max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL', null=True),
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee / price in BDT', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='Estimated duration in minutes')),
                ('preparation_instructions', models.TextField(blank=True, default='', help_text='e.g. Overnight fasting required')),
                ('is_available', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_services', to='clinics.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Service',
                'verbose_name_plural': 'Clinic Services',
                'ordering': ['name'],
            },
        ),
    ]
