# Generated by Django 5.0.14 on 2026-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_description_clinic_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of clinic photos with id, image_url, title, category, description, is_featured'),
        ),
    ]
