# Generated by Django 5.0.14 on 2026-09-15 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinic_gallery'),
        ('doctors', '0007_chambersession_announcement_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('DOCTOR_VISIT', 'Doctor Visit / Special Chamber'), ('SCHEDULE_CHANGE', 'Schedule Change'), ('NEW_SERVICE', 'New Service'), ('CLINIC_NOTICE', 'Clinic Notice'), ('HOLIDAY', 'Holiday / Closure'), ('GENERAL', 'General Announcement')], db_index=True, default='GENERAL', max_length=30)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date the event/visit is scheduled', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Time the event/visit starts', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When to start showing this announcement', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing this announcement', null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_announcements', to='doctors.doctor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
