# Generated by Django 5.0.14 on 2026-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinicstaff_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicstaff',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
