# Generated by Django 5.0.14 on 2026-09-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinicstaff_monthly_salary'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='common.district'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='common.division'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='common.upazila'),
        ),
    ]
