# Generated by Django 5.0.14 on 2026-09-30 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinic_district_clinic_division_clinic_upazila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClosingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shift_date', models.DateField()),
                ('shift_end_time', models.TimeField()),
                ('system_cash_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('physical_cash_counted', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('digital_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tokens_handled', models.IntegerField(default=0)),
                ('total_transactions_count', models.IntegerField(default=0)),
                ('denominations', models.JSONField(blank=True, default=dict, help_text="Breakdown of currency counts: {'1000': 10, '500': 5, ...}")),
                ('handed_over_to', models.CharField(blank=True, default='', help_text='Name of supervisor or next duty receptionist', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_closings', to='clinics.clinic')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Closing Log',
                'verbose_name_plural': 'Shift Closing Logs',
                'ordering': ['-shift_date', '-shift_end_time'],
            },
        ),
    ]
