# Generated by Django 5.0.14 on 2026-09-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('CASH', 'Cash at Chamber'), ('STRIPE', 'Stripe'), ('SSLCOMMERZ', 'SSLCommerz'), ('PAYPAL', 'PayPal')], default='BKASH', max_length=20),
        ),
    ]
