# Generated by Django 5.0.14 on 2026-09-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_currency_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_tran_id',
            field=models.CharField(blank=True, default='', help_text='Bank transaction ID', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, default='', help_text='Card or MFS type (e.g. BKASH-BKash)', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, default='', help_text='SSLCommerz validation ID', max_length=255),
        ),
    ]
